name: poultry_app
description: "A mobile app to measure soil activity and predict the best time to plant crops. It uses sensors to measure soil activity and provides a user-friendly interface for farmers to track their soil health."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  google_sign_in: ^6.1.6
  audioplayers: ^6.4.0
  fl_chart: ^1.0.0
  audio_waveforms: ^1.3.0
  file_picker: ^10.1.9
  supabase_flutter: ^2.9.1
  connectivity_plus: ^5.0.2
  http: ^1.0.0
  uuid: ^4.5.1
  just_audio: ^0.9.0
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 24
  image_path: "lib/assets/images/poultry_app_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/poultry_app_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/icons/

  fonts:
    - family: Lexend
      fonts:
        - asset: lib/assets/fonts/Lexend/Lexend-Regular.ttf
        - asset: lib/assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800

    - family: Urbanist
      fonts:
        - asset: lib/assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
